name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
        docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/zqzzq2/k12:1.0
        docker push registry.cn-hangzhou.aliyuncs.com/zqzzq2/k12:1.0
